### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by bjlittle** [informatics-lab/forest#111]
@andrewgryan The project hasn't yet turned on Travis CI testing. It probably should... I'm happy to do that, if you want.

Can you provide me an example of how you run all your tests, and I'll add the necessary parts to `setup.py` and `.travis.yml`.

Confusingly for me (as I'm none the wiser) you have tests in the top-level `test/_test_*.py` directory, and also the `forest/test_*.py` directory. Do both of these require to be run? What's the difference between them?

**Comment by andrewgryan** [comment]
Hi Bill,

The tests should run with ``python -m unittest discover`` from inside the **test/** directory. But the current version of ``master`` the tests in **forest/** are the ones that are being used. 

I have a branch called ``viewer`` that is decoupling the menu system so that it can run with either SQL or FileSystem meta-data. In that branch, I have removed the ``_test*.py`` files and begun to migrate all tests to the **test/** directory.

You could set up Travis to run the tests in **forest/** and then when/if the **test/** directory is back in action we can point it at that. Also, I think the Travis CI web hook is already active but as you say the .travis.yml isn't doing anything interesting

https://travis-ci.com/informatics-lab/forest

**Comment by andrewgryan** [comment]
@bjlittle changes in the `simple_cli` branch which are to be merged back today put all of the tests into the `test` directory and support the use of `pytest`, hopefully the code changes related to this issue should be easy to implement then
